# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import random
from PyQt5 import QtCore, QtGui, QtWidgets
from shelvingManager.Backend.Controller.database_controller import DatabaseController
from shelvingManager.Backend.Controller.item_controller import ItemController
from shelvingManager.Backend.Controller.shelving_controller import ShelvingController
from shelvingManager.Backend.Controller.item_type_controller import ItemTypeController
from shelvingManager.Backend.Controller.shelf_controller import ShelfController


class Ui_Dialog(object):

    MAX_DESCRIPTION_CHARACTERS = 255
    dbc = DatabaseController()
    ic = ItemController(dbc.conn)
    sc = ShelvingController(dbc.conn)
    it = ItemTypeController(dbc.conn)
    sfc = ShelfController(dbc.conn)

    shelving_id = None
    shelving = None
    shelves = []
    items = []
    item_types = []

    def setupUi(self, Dialog, row_count, column_count, shelving_id):
        self.shelving_id = shelving_id
        self.shelving = self.sc.get_shelving(shelving_id)
        self.shelves = self.sfc.get_shelves_by_shelving_id(shelving_id)
        for shelf in self.shelves:
            self.items.append(self.ic.get_items_by_shelf_id(shelf.id))
        self.item_types = self.it.get_all_item_types()
        Dialog.setObjectName("Dialog")
        Dialog.resize(1284, 590)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setFixedSize(1284, 590)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(
            QtCore.QRect(30, 10, 1201, 541))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout_4.setSizeConstraint(
            QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(
            10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.textName_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.textName_2.setMaxLength(20)
        self.textName_2.setCursorPosition(0)
        self.textName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textName_2.setObjectName("textName_2")
        self.horizontalLayout.addWidget(self.textName_2)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(10, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(
            10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.etDescription = QtWidgets.QPlainTextEdit(
            self.horizontalLayoutWidget)
        self.etDescription.setMaximumSize(QtCore.QSize(16777215, 100))
        self.etDescription.setObjectName("etDescription")
        self.horizontalLayout_3.addWidget(self.etDescription)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(10, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.spinBox_3 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_3.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_12.addWidget(self.spinBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.spinBox_2 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_9.addWidget(self.spinBox_2)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.buttonBox = QtWidgets.QDialogButtonBox(
            self.horizontalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(column_count)
        self.tableWidget.setRowCount(row_count)
        self.tableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)
        h_header = self.tableWidget.horizontalHeader()
        h_header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        v_header = self.tableWidget.verticalHeader()
        v_header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.etDescription.textChanged.connect(self.limit_text)
        self.spinBox_2.valueChanged.connect(self.draw_table)
        self.spinBox_3.valueChanged.connect(self.draw_table)
        self.buttonBox.accepted.connect(self.control_item_position)
        self.tableWidget.clicked.connect(self.deactivate_selection)
        self.deactivate_selection()
        self.buttonBox.accepted.connect(self.insert_item)
        self.spinBox_2.valueChanged.connect(self.control_item_position)
        self.spinBox_3.valueChanged.connect(self.control_item_position)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.textName_2.textChanged.connect(self.control_buttons)
        self.comboBox.currentTextChanged.connect(self.control_buttons)
        self.control_buttons()
        self.spinBox_2.setMinimum(1)
        self.spinBox_3.setMinimum(1)
        self.spinBox_2.setMaximum(column_count)
        self.spinBox_3.setMaximum(row_count)
        self.comboBox.currentTextChanged.connect(self.draw_table)
        self.load_item_types()
        self.populate_table()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nuevo objeto"))
        self.label.setText(_translate("Dialog", "Nombre"))
        self.textName_2.setPlaceholderText(
            _translate("Dialog", "Max. 20 caracteres"))
        self.label_2.setText(_translate("Dialog", "Tipo de objeto"))
        self.label_4.setText(_translate("Dialog", "Descripción:"))
        self.etDescription.setPlaceholderText(
            _translate("Dialog", "Max. 255 caracteres"))
        self.label_3.setText(_translate("Dialog", "Posición"))
        self.label_9.setText(_translate("Dialog", "Balda"))
        self.label_7.setText(_translate("Dialog", "Inicio"))
        self.label_8.setText(_translate("Dialog", "Fin"))

    def load_item_types(self):
        self.comboBox.clear()
        self.comboBox.addItem("")
        for item_type in self.item_types:
            self.comboBox.addItem(item_type.name)

    def insert_item(self):
        name = self.textName_2.text()
        description = self.etDescription.toPlainText()
        shelf_position = self.spinBox_3.value() - 1
        item_type = self.it.get_item_type(self.comboBox.currentText())
        length = int((item_type.size - 10) / 10)
        shelf_id = self.sfc.get_shelf_by_shelving_id_and_shelf_pos(self.shelving_id, shelf_position).id
        item_type_id = self.it.get_item_type(self.comboBox.currentText()).id
        start_position = self.spinBox_2.value() - 1
        end_position = start_position + length
        self.ic.insert_item(name, shelf_id, item_type_id, start_position, end_position, description)

    def control_item_position(self):
        occupied_cells = []
        insert_try = []
        if(self.comboBox.currentText() != ""):
            item_type = self.it.get_item_type(self.comboBox.currentText())
            length = int((item_type.size - 10) / 10)
            height = len(self.shelves) - 1
            end_position = self.spinBox_2.value() - 1 + length
            for shelf in self.shelves:
                for item in self.ic.get_items_by_shelf_id(shelf.id):
                    row = height - shelf.position
                    position_occupied = self.ic.get_item_position(item.id)
                    for i in range(position_occupied[0], position_occupied[1] + 1):
                        occupied_cells.append((row, i))

                    if insert_try == []:
                        for i in range(self.spinBox_2.value() - 1, end_position + 1):
                            insert_try.append((height - self.spinBox_3.value() + 1, i))
                    else:
                        for i in range(self.spinBox_2.value() - 1, end_position + 1):
                            insert_try.append((height - self.spinBox_3.value() + 1, i))

            for i in occupied_cells:
                for j in insert_try:
                    if(j == i):
                        self.label_5.setText(
                            "<font color='red'>Ya hay uno o más objetos en esta posición.</font>")
                        self.buttonBox.setEnabled(False)
                        return
                    else:
                        self.label_5.setText("")
                        self.buttonBox.setEnabled(True)

    def draw_table(self):
        self.tableWidget.clear()
        height = len(self.shelves)
        if(self.comboBox.currentText() != ""):
            item_type = self.it.get_item_type(self.comboBox.currentText())
            length = (item_type.size - 10) / 10
            self.tableWidget.setRangeSelected(QtWidgets.QTableWidgetSelectionRange(height - self.spinBox_3.value(
            ), self.spinBox_2.value() - 1, height - self.spinBox_3.value(), self.spinBox_2.value() - 1 + length), True)
        self.populate_table()

    def deactivate_selection(self):
        self.tableWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.NoSelection)

    def populate_table(self):
        positions = []
        shelves = self.sfc.get_shelves_by_shelving_id(self.shelving_id)
        height = len(shelves) - 1
        shelves = self.sfc.get_shelves_by_shelving_id(self.shelving_id)
        for shelf in shelves:
            items = self.ic.get_items_by_shelf_id(shelf.id)
            for item in items:
                position_occupied = self.ic.get_item_position(item.id)
                positions.append(position_occupied)
                for i in range(position_occupied[0], position_occupied[1] + 1):
                    if self.tableWidget.item(height - shelf.position, i) is None:
                        self.tableWidget.setItem(
                            height - shelf.position, i, QtWidgets.QTableWidgetItem(str(item.name)))
                        self.tableWidget.item(
                            height - shelf.position, i).setBackground(QtGui.QColor(255, 0, 0))
                    else:
                        item = self.tableWidget.item(
                            height - shelf.position, i)
                        color = item.background()
                        self.tableWidget.setItem(
                            height - shelf.position, i, item)
                        self.tableWidget.item(
                            height - shelf.position, i).setBackground(color)

    def control_buttons(self):
        if self.textName_2.text() == "" or self.comboBox.currentText() == "":
            self.buttonBox.setEnabled(False)
        else:
            self.buttonBox.setEnabled(True)

    def limit_text(self):
        text = self.etDescription.toPlainText()
        if text is not None:
            if len(text) > self.MAX_DESCRIPTION_CHARACTERS:
                self.label_5.setText(
                    "<font color='red'>Max. 255 caracteres</font>")
                self.etDescription.setPlainText(text[:255])
            elif len(text) == self.MAX_DESCRIPTION_CHARACTERS - 1:
                self.label_5.setText("")

    def item_window(self, row_count, column_count, shelving_id):
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog, row_count, column_count, shelving_id)
        Dialog.show()
        Dialog.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        Dialog.exec_()
