
--TABLES CREATION--
CREATE TABLE IF NOT EXISTS rooms (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT(20) NOT NULL,
    description TEXT(255),
    positions TEXT NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shelvings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    room_id INTEGER NOT NULL,
    code TEXT(3) NOT NULL,
    description TEXT(255),
    position INTEGER NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (room_id) REFERENCES rooms(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS shelves (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    shelving_id INTEGER NOT NULL,
    name TEXT(6) NOT NULL,
    description TEXT(255),
    position INTEGER NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shelving_id) REFERENCES shelvings(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS item_types (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT(20) NOT NULL,
    description TEXT(255),
    size INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    shelf_id INTEGER,
    item_type_id INTEGER NOT NULL,
    position TEXT NOT NULL,
    name TEXT(25) NOT NULL,
    description TEXT(255),
    FOREIGN KEY (shelf_id) REFERENCES shelves(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
    FOREIGN KEY (item_type_id) REFERENCES item_types(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);